version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-redis-auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql_workbench
    depends_on:
      - mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - workbench_data:/config
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  workbench_data:
    driver: local
